### ISSUE TITLE
make -C arch64-ubuntu1604 libsnowboy-detect.a make[1]: *** arch64-ubuntu1604: No such file or directory. Stop. make: *** [Makefile:67: arch64-ubuntu1604/libsnowboy-detect.a] Error 2

### ISSUE THREAD

**Issue by liliang9693** [wzpan/wukong-contrib#102]
按照官方教程给unihiker手动安装进行到构建snowboy的时候报错说找不到文件夹:
![image](https://user-images.githubusercontent.com/20766471/234752887-896f358a-7d2b-48c9-91db-cc1a2f6ec71a.png)

**Comment by wzpan** [comment]
已经修复，请重新下载这个 snowboy.tar.bz2 包重试下。

**Comment by liliang9693** [comment]
使用最新的git包安装成功了，感谢

**Comment by liliang9693** [comment]
tips：使用行空板0.3.5固件选择英文语言的时候，安装wukong完成之后运行python3 wukong.py的时候报了个如下时区冲突的错误，通过在终端运行export TZ=Asia/Shanghai可以解决。

Traceback (most recent call last):
  File "wukong.py", line 188, in <module>
    wukong.run()
  File "wukong.py", line 88, in run
    self.init()
  File "wukong.py", line 55, in init
    self.conversation = Conversation(self._profiling)
  File "/root/wukong-robot/robot/Conversation.py", line 41, in __init__
    self.scheduler = Scheduler(self)
  File "/root/wukong-robot/robot/Scheduler.py", line 34, in __init__
    self._sched = BackgroundScheduler()
  File "/usr/local/lib/python3.7/dist-packages/apscheduler/schedulers/base.py", line 87,                                                                                               in __init__
    self.configure(gconfig, **options)
  File "/usr/local/lib/python3.7/dist-packages/apscheduler/schedulers/base.py", line 131,                                                                                               in configure
    self._configure(config)
  File "/usr/local/lib/python3.7/dist-packages/apscheduler/schedulers/background.py", lin                                                                                              e 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/usr/local/lib/python3.7/dist-packages/apscheduler/schedulers/base.py", line 701,                                                                                               in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/usr/local/lib/python3.7/dist-packages/tzlocal/unix.py", line 209, in get_localzo                                                                                              ne
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.7/dist-packages/tzlocal/unix.py", line 171, in _get_localz                                                                                              one
    tzname = _get_localzone_name(_root)
  File "/usr/local/lib/python3.7/dist-packages/tzlocal/unix.py", line 150, in _get_localz                                                                                              one_name
    raise utils.ZoneInfoNotFoundError(message)
tzlocal.utils.ZoneInfoNotFoundError: 'Multiple conflicting time zone configurations found                                                                                              :\n/etc/timezone: Etc/UTC\n/etc/localtime is a symlink to: PRC\nFix the configuration, or                                                                                               set the time zone in a TZ environment variable.\n'
^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
