### ISSUE TITLE
网易云音乐插件无法加载

### ISSUE THREAD

**Issue by telanflow** [wzpan/wukong-contrib#76]
## 用户贡献技能
网易云音乐插件无法加载

## 环境
用户贡献插件存放：`~/.wukong/contrib`
悟空项目：`~/wukong-robot`

两个项目依赖的安装分别是用 virtualenv 创建的虚拟环境 venv

## 错误Log
```
INFO:robot.ASR:使用 xunfei-asr ASR 引擎
INFO:robot.AI:使用 emotibot 对话机器人
INFO:robot.TTS:使用 xunfei-tts TTS 引擎
INFO:robot.NLU:使用 unit NLU 引擎
INFO:robot.plugin_loader:插件 Camera 已被禁用
INFO:robot.plugin_loader:插件 CleanCache 加载成功 
INFO:robot.plugin_loader:插件 Echo 加载成功 
INFO:robot.plugin_loader:插件 Email 加载成功 
INFO:robot.plugin_loader:插件 Geek 加载成功 
INFO:robot.plugin_loader:插件 LocalPlayer 加载成功 
INFO:robot.plugin_loader:插件 Poem 加载成功 
INFO:robot.plugin_loader:插件 Volume 加载成功 
INFO:robot.plugin_loader:插件 BaiduFM 加载成功 
INFO:robot.plugin_loader:插件 BaiduMap 加载成功 
INFO:robot.plugin_loader:插件 ControMqtt 加载成功 
INFO:robot.plugin_loader:插件 Direction 加载成功 
INFO:robot.plugin_loader:插件 EmailMyPC 加载成功 
INFO:robot.plugin_loader:插件 Halt 加载成功 
INFO:robot.plugin_loader:插件 Hass 加载成功 
INFO:robot.plugin_loader:插件 HeadlineNews 加载成功 
INFO:robot.plugin_loader:插件 Lamp 加载成功 
WARNING:robot.plugin_loader:插件 NeteaseMusic 加载出错，跳过
Traceback (most recent call last):
  File "/Users/telan/work/wukong-robot/robot/plugin_loader.py", line 36, in init_plugins
    mod = loader.load_module(name)
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/telan/.wukong/contrib/NeteaseMusic.py", line 11, in <module>
    from sdk import NetEaseApi
  File "/Users/telan/.wukong/contrib/sdk/NetEaseApi.py", line 21, in <module>
```

是虚拟环境导致的吗？sdk包加载不了

**Comment by telanflow** [comment]
然后我试过在wukong-robot项目的虚拟环境下面安装contrib项目的依赖
```
pip3 install -r ~/.wukong/contrib/requirements.txt
```

**Comment by telanflow** [comment]
我知道了，contrib 项目的requirements.txt 少了一个包:  pycryptodome 
```
pip3 install pycryptodome
```
我安装上就好了

**Comment by telanflow** [comment]
### 我已经提交pull requests把这个库添加到requirements.txt

**Comment by wzpan** [comment]
好，我补一个依赖
