### ISSUE TITLE
如果是win10子系统，请执行以下命令:  sudo pip3 install --upgrade --ignore-installed -r requirements.txt

### ISSUE THREAD

**Issue by 19969140607** [wzpan/wukong-contrib#86]
还是不行

**Comment by 19969140607** [comment]
Traceback (most recent call last):
  File "/home/llj/wukong-robot/snowboy/snowboydetect.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'snowboy._snowboydetect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wukong.py", line 15, in <module>
    from snowboy import snowboydecoder
  File "/home/llj/wukong-robot/snowboy/snowboydecoder.py", line 5, in <module>
    from . import snowboydetect
  File "/home/llj/wukong-robot/snowboy/snowboydetect.py", line 17, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/llj/wukong-robot/snowboy/snowboydetect.py", line 16, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_snowboydetect'

**Comment by wzpan** [comment]
你需要自行编译一下snowboy，详见：https://wukong.hahack.com/#/install?id=_4-%e7%bc%96%e8%af%91-_snowboydetectso
