### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by Culturenotes** [wzpan/wukong-contrib#91]
INFO:__main__:开始录音
INFO:robot.Conversation:结束录音
INFO:robot.ASR:baidu-asr 语音识别到了：['音量小些。']
INFO:robot.Brain:'音量小些。' 命中技能 Volume
CRITICAL:robot.Brain:Failed to execute plugin
Traceback (most recent call last):
  File "/home/l/wukong-robot/robot/Brain.py", line 85, in query
    continueHandle = plugin.handle(text, parsed)
  File "/home/l/wukong-robot/plugins/Volume.py", line 26, in handle
    self.player.turnDown()
  File "/home/l/wukong-robot/robot/Player.py", line 248, in turnDown
    universal_newlines=True,
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
INFO:robot.TTS:han-tts 语音合成成功，合成路径：/tmp/tmp4grh18g5
其他插件都没有问题，配置过后可以正常使用，但是就是这个调节音量不好用？这是什么问题啊？

**Comment by wzpan** [comment]
已确认 `capture_output` 这个是 Python 3.7 之后才有的参数，建议升级到 Python 3.7。
近期我将修改下 Python 环境要求，版本提升到 3.7+ 。
